default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV['DB_HOST'] %>
  username: <%= ENV['DB_USERNAME'] %>
  password: <%= ENV['DB_PASSWORD'] %>

development:
  <<: *default
  database: mcconnect_development

test:
  <<: *default
  database: mcconnect_test

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
